### ISSUE TITLE
(*Transport.)close: nil pointer dereference of handlerMap

### ISSUE THREAD

**Issue by kelmenhorst** [quic-go/quic-go#3906]
Hi, 
I noticed that in some cases, `(*Transport.)close` causes a nil pointer dereference due to `(Transport.)handlerMap` being uninitialized. 

Minimal example to reproduce when using [DialEarly](https://github.com/quic-go/quic-go/blob/85764da3b65997a229a961d9704a03e6c02a682b/client.go#LL90C6-L90C15):
```
addr, _ := net.ResolveUDPAddr("udp", "google.com:443")
conn, _ := net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4zero, Port: 0, Zone: ""})
var invalidVersion quic.VersionNumber = 0x3      // <-- there is no v3, so validateConfig will fail
qconf := &quic.Config{
	Versions: []quic.VersionNumber{
		invalidVersion,
	},
}
quic.DialEarly(context.Background(), conn, addr, <*tls.Config>, qconf)
```

I get the following output:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x837680]

goroutine 18 [running]:
testing.tRunner.func1.2({0xa96480, 0xffe130})
	/usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0xa96480, 0xffe130})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/quic-go/quic-go.(*Transport).close(0xc0003c41c0, {0xc6d140, 0xc0003943d0})
	/home/kelmenhorst/go/pkg/mod/github.com/quic-go/quic-go@v0.35.1/transport.go:270 +0x100
github.com/quic-go/quic-go.(*Transport).Close(0xc0003c41c0)
	/home/kelmenhorst/go/pkg/mod/github.com/quic-go/quic-go@v0.35.1/transport.go:232 +0x6b
github.com/quic-go/quic-go.DialEarly({0xc73a70, 0xc00003e0b8}, {0xc76620?, 0xc0003960a0?}, {0xc71358, 0xc000392a80}, 0xc0003c0300, 0x55cff4?)
	/home/kelmenhorst/go/pkg/mod/github.com/quic-go/quic-go@v0.35.1/client.go:97 +0x190
```

Am I missing something here? 
If not, I suggest to add a check in `(*Transport.)close` before trying to close the `t.handlerMap`.

Edit: Similarly `(*Transport.)Close` assumes `t.conn` and `t.listening` to be initialized which is not always the case (again referring to the example code above).

**Comment by marten-seemann** [comment]
Sounds reasonable. Want to submit a patch?
