### ISSUE TITLE
inconsistent packet size

### ISSUE THREAD

**Issue by master255** [quic-go/quic-go#4108]
Libp2p version 0.31, quic-go@v0.38.1
I am starting the application with only 4G network.
Then I turn on WIFI. The application shuts down with this error:
```
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  panic: inconsistent packet size (28 vs 1402)
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  goroutine 19275 [running]:
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  github.com/quic-go/quic-go.(*sconn).Write(0x4001b3b180, {0x40004fb000, 0x1c, 0x5000}, 0x57a)
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  	/home/oleg/go/pkg/mod/github.com/quic-go/quic-go@v0.38.1/send_conn.go:66 +0x2bc
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  github.com/quic-go/quic-go.(*sendQueue).Run(0x40021ba3f0)
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  	/home/oleg/go/pkg/mod/github.com/quic-go/quic-go@v0.38.1/send_queue.go:80 +0x124
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  github.com/quic-go/quic-go.(*connection).run.func2()
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  	/home/oleg/go/pkg/mod/github.com/quic-go/quic-go@v0.38.1/connection.go:508 +0x30
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  created by github.com/quic-go/quic-go.(*connection).run in goroutine 19273
--------- beginning of crash
2023-10-08 20:45:41.085 19676-0     Go                      com.media.library                    E  	/home/oleg/go/pkg/mod/github.com/quic-go/quic-go@v0.38.1/connection.go:507 +0x144
2023-10-08 20:45:41.086 19676-20073 libc                    com.media.library                    A  Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 20073 (m.media.library), pid 19676 (m.media.library)
```

Any other network switching for example WIFI->4G error does not occur.

**Comment by marten-seemann** [comment]
Does this reproduce with v0.39? This code was changed recently, and if it doesn't reproduce, there's no point in debugging this.

**Comment by master255** [comment]
I don't know. Update quick in Libp2p and then I can check.

**Comment by master255** [comment]
Can't compile. Errors:
![image](https://github.com/quic-go/quic-go/assets/5380115/c9a223ff-1b05-4ef9-aadc-e69bc45beb5a)

```
gomobile: go build -ldflags -s -w -buildmode=c-shared -o=/tmp/gomobile-work-3381159102/android/src/main/jniLibs/x86/libgojni.so ./gobind failed: exit status 1
# github.com/lucas-clemente/quic-go/internal/qtls
/home/oleg/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
# github.com/libp2p/go-libp2p/p2p/net/nat
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/nat/nat.go:141:42: not enough arguments in call to nat.nat.DeletePortMapping
        have (string, int)
        want (context.Context, string, int)
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/nat/nat.go:168:82: not enough arguments in call to nat.nat.AddPortMapping
        have (string, int, string, time.Duration)
        want (context.Context, string, int, string, time.Duration)
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/nat/nat.go:171:82: not enough arguments in call to nat.nat.AddPortMapping
        have (string, int, string, number)
        want (context.Context, string, int, string, time.Duration)
# github.com/libp2p/go-libp2p/p2p/net/upgrader
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/upgrader/upgrader.go:56:14: cannot use generic type multistream.MultistreamMuxer[T multistream.StringLike] without instantiation
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/upgrader/upgrader.go:61:17: cannot use generic type multistream.MultistreamMuxer[T multistream.StringLike] without instantiation
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/upgrader/upgrader.go:80:41: cannot infer T (/home/oleg/go/pkg/mod/github.com/multiformats/go-multistream@v0.4.1/multistream.go:58:26)
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/net/upgrader/upgrader.go:83:41: cannot infer T (/home/oleg/go/pkg/mod/github.com/multiformats/go-multistream@v0.4.1/multistream.go:58:26)
# github.com/libp2p/go-libp2p/p2p/host/blank
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/host/blank/blank.go:30:12: cannot use generic type multistream.MultistreamMuxer[T multistream.StringLike] without instantiation
/mnt/c/Users/Oleg/Documents/go-libp2p/p2p/host/blank/blank.go:68:36: cannot infer T (/home/oleg/go/pkg/mod/github.com/multiformats/go-multistream@v0.4.1/multistream.go:58:26)
# github.com/libp2p/go-libp2p-kad-dht
/home/oleg/go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.25.1/subscriber_notifee.go:135:52: cannot use dht.protocols (variable of type []protocol.ID) as []string value in argument to dht.peerstore.FirstSupportedProtocol
```

**Comment by marten-seemann** [comment]
It builds on CI, do the problem is clearly on your side. I can’t help you debug gomobile though.

**Comment by master255** [comment]
It's a bug in the quic library that you ignored.

**Comment by master255** [comment]
Okay. That was my fault with the gomobile. I fixed it. The new Quic version 0.39 does not have this bug.
